FROM node:18.16.0
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm i

# Copy the rest of the files into the container
COPY . .

# Generate the prisma client
RUN npx prisma generate

# Transpile the TypeScript code into JavaScript
RUN npm run build

CMD ["npm", "run", "prod"]