import { Request as JWTRequest } from 'express-jwt';

enum NOTIFICATION_TYPE {
  BOSSDROP = 'BOSSDROP',
  CLUEITEM = 'CLUEITEM',
  COFFERDEPOSIT = 'COFFERDEPOSIT',
  COFFERWITHDRAW = 'COFFERWITHDRAW',
  COLLECTIONLOG = 'COLLECTIONLOG',
  COMBATACHIEVEMENT = 'COMBATACHIEVEMENT',
  DIARYCOMPLETION = 'DIARYCOMPLETION',
  HARDCOREDEATH = 'HARDCOREDEATH',
  LEVELUP = 'LEVELUP',
  PERSONALBEST = 'PERSONALBEST',
  PKLOSE = 'PKLOSE',
  PKWIN = 'PKWIN',
  QUESTCOMPLETION = 'QUESTCOMPLETION',
  TEST = 'TEST'
}

const titles = {
  [NOTIFICATION_TYPE.BOSSDROP]: 'Drop',
  [NOTIFICATION_TYPE.CLUEITEM]: 'Clue Scroll Item',
  [NOTIFICATION_TYPE.COFFERDEPOSIT]: 'Coffer',
  [NOTIFICATION_TYPE.COFFERWITHDRAW]: 'Coffer',
  [NOTIFICATION_TYPE.COLLECTIONLOG]: 'Collection Log',
  [NOTIFICATION_TYPE.COMBATACHIEVEMENT]: 'Comabt Achievemnt',
  [NOTIFICATION_TYPE.DIARYCOMPLETION]: 'Diary',
  [NOTIFICATION_TYPE.HARDCOREDEATH]: 'Hardcore Death',
  [NOTIFICATION_TYPE.LEVELUP]: 'Level Up',
  [NOTIFICATION_TYPE.PKLOSE]: 'You Lost',
  [NOTIFICATION_TYPE.PKWIN]: 'You Won',
  [NOTIFICATION_TYPE.PERSONALBEST]: 'Personal Best',
  [NOTIFICATION_TYPE.QUESTCOMPLETION]: 'Quest Complete',
  [NOTIFICATION_TYPE.TEST]: 'Testing'
};

export class NotificationRequest {
  type: NOTIFICATION_TYPE;
  message: string;
  rsn: string;
}

export function getTitle(type: NOTIFICATION_TYPE) {
  return titles[type];
}
